# coding: utf-8

# flake8: noqa
"""
    Flight Booking System

    Book and manage flight tickets

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from flight_sdk.models.booking_create import BookingCreate
from flight_sdk.models.booking_out import BookingOut
from flight_sdk.models.flight_create import FlightCreate
from flight_sdk.models.flight_out import FlightOut
from flight_sdk.models.http_validation_error import HTTPValidationError
from flight_sdk.models.validation_error import ValidationError
from flight_sdk.models.validation_error_loc_inner import ValidationErrorLocInner
