# coding: utf-8

"""
    Flight Booking System

    Book and manage flight tickets

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flight_sdk.models.booking_out import BookingOut

class TestBookingOut(unittest.TestCase):
    """BookingOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BookingOut:
        """Test BookingOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BookingOut`
        """
        model = BookingOut()
        if include_optional:
            return BookingOut(
                id = 56,
                passenger_name = '',
                passport_number = '',
                flight_id = 56,
                is_cancelled = True
            )
        else:
            return BookingOut(
                id = 56,
                passenger_name = '',
                passport_number = '',
                flight_id = 56,
                is_cancelled = True,
        )
        """

    def testBookingOut(self):
        """Test BookingOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
